apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redissvc
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
