version: '3.7'

networks:
  challenge_net:
    internal: true

services:

  server:
    image: "fl_challenge:team_name"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      challenge_net:
        aliases:
          - server
    environment:
      - FLWR_TELEMETRY_ENABLED=0
    volumes:
      - ./src/server:/app/code:rw
      - ./data/output:/app/output

  client1:
    image: "fl_challenge:team_name"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - gpus=all
    depends_on: [ server ]
    environment:
      - FLWR_TELEMETRY_ENABLED=0
      - CLIENT_NR=1
    networks:
      - challenge_net
    volumes:
      - ./src/client:/app/code:rw
      - ./data/input:/app/input:ro
      - ./data/output:/app/output

  client2:
    image: "fl_challenge:team_name"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ server ] 
    environment:
      - FLWR_TELEMETRY_ENABLED=0
      - CLIENT_NR=1
    networks:
      - challenge_net
    volumes:
      - ./src/client:/app/code:rw
      - ./data/input:/app/input:ro
      - ./data/output:/app/output

  hacker:
    image: "fl_challenge:team_name"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ server ]
    environment:
      - FLWR_TELEMETRY_ENABLED=0
    networks:
      - challenge_net
    volumes:
      - ./src/hacker:/app/code:rw
      - ./data/input:/app/input:ro
      - ./data/output:/app/output
